export enum WebSocketKey {
  SHIPMENT_TRACKING = 'SHIPMENT_TRACKING',
  DRIVER_LOCATION = 'DRIVER_LOCATION',
  LOAD_STATUS_UPDATES = 'LOAD_STATUS_UPDATES',
  NOTIFICATIONS = 'NOTIFICATIONS',
  MOCK_CHAT = 'MOCK_WS_ENDPOINT',
}
